### ISSUE TITLE
3.0.0 release

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-tooltips#109]
Changes that need to be made for the `3.0.0` release:

- [x] Deprecate all properties that throw a deprecation warning in the 2.3.2 (#125)
- [x] Set `enableLazyRendering` to true by default (#125)
- [x] Remove `<x>-on-component` and `<x>-on-element` in favor of `ember-<x>` and an `isTargetComponent` property
- [x] Add publicly available test helpers for consuming apps (#114)
- [x] Deprecate `delay` in favor of `showDelay` (#125)
- [x] Fix IE multi line bug (#137)
- [x] Add code linting (#154)
- [x] Fix #152 by making `ember-hash-helper-polyfill` a required `peerDependency` for apps using Ember less than `2.3.0`.

**Comment by sir-dunxalot** [comment]
@a15n Anything else we want to add to this list? I created a `3.0.0 milestone` to group anything else relevant to this release.

**Comment by a15n** [comment]
I think that's it for now. Thanks for making this ticket

**Comment by a15n** [comment]
Maybe remove CSS styles from the tooltip. I had expected the popovers to be completely unstyled. At least in my app I'm having to override a lot of these styles...

https://github.com/sir-dunxalot/ember-tooltips/commit/bc55092cc30de896c0ad7ea13a02e1b60e6b8ae3#commitcomment-19321234

**Comment by sir-dunxalot** [comment]
So that's an interesting discussion. For the majority of developers, I think this should be a plug-and-play solution where tooltips will work with an install but you can customize them with additional work. Maybe there is an alternative where an option can be set that would exclude the styles from being concatenated into the consuming app's `vendor.css` file. This option could be set in the `ember-cli-build` file.

**Comment by a15n** [comment]
You bring up a good point with the plug-and-play majority needs. I think since that's the case the current approach is good.

**Comment by sir-dunxalot** [comment]
Ok, sounds good. Happy to explore the option of excluding stylesheets if that would alleviate the pain for those who do overwrite tooltip and popover styles.

**Comment by sir-dunxalot** [comment]
@a15n Thoughts on adding publicly available test helpers for consuming apps that test tooltips?

**Comment by a15n** [comment]
Good idea. Can you message me with how to best do this?

**Comment by sir-dunxalot** [comment]
I've done the first couple of steps on [this branch](https://github.com/sir-dunxalot/ember-tooltips/tree/public-test-helpers). The new file is in the `/test-support` directory.

I would like to make helpers available for the following:

- Asserting tooltip visibility (hiding and showing)
- Asserting popover visibility (hiding and showing)
- Clicking on a target
- Hitting esc to close a tooltip/popover
- Clicking outside a popover

I'm sure there are others that could be beneficial but this would be a good start.

**Comment by a15n** [comment]
I think http://ember-cli-page-object.js.org/docs/v1.6.x/ will be very useful for this. I'll start working on the test helper branch without it and I'll message here if page-object would be needed.

**Comment by a15n** [comment]
Maybe we should deprecate `delay` in favor of `showDelay`? It's more explicit, especially with `hideDelay` available on popovers

**Comment by sir-dunxalot** [comment]
I have added that as fifth requirement since it should be simple to take care of when removing deprecation warnings for other properties. With #114 in review I suspect the only other item that will need a lot of time is this one:

> Remove ember-<x>-on-component and ember-<x>-on-element in favor of ember-<x> and an isTargetComponent property

Would you agree? I'm going to be leaning on you for that change due to your more intimate knowledge of how the lazy wrapper works. I can take care of the other small changes in a PR.

Then we should be good to review and release `3.0.0`. Sounds good?

**Comment by a15n** [comment]
I'll be able to make that change. Do we want a version of semver that supports `tooltip-on-element`, `tooltip-on-component`, and the `ember-tooltip` (with isTargetComponent)? I was thinking we have something like 2.9.0 (or whatever) that will support all of these so that people can use that version to transition to the single component approach. We will then remove support for `<x>-on-<y>` in 3.0.0.

**Comment by sir-dunxalot** [comment]
A 2.x release sounds good. Is that going to create a lot of additional work for maintaining the test suite changes pre 3.0.0? Also, I opened #125 for the deprecation of properties as I'm sure you've seen.

**Comment by sir-dunxalot** [comment]
`3.0.0` has been released!
