### ISSUE TITLE
Add more test helpers

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-tooltips#128]
#114 introduces public test helpers for asserting that a tooltip is shown and hidden.

We should also provide test helpers for:

- [x] Asserting tooltip content matches a string (#146)
- [x] Asserting a tooltip is positioned correctly on a given element's side (#143)
- [x] Asserting a tooltip is a given number of pixels from the target on a given side (#145)

**Comment by ryanlabouve** [comment]
Great work on the test helpers! Started using them today in a large app.

I'd be happy to help with "Asserting tooltip content matches a string". Or if you already have it in the works, no big deal! Great addon. Just trying to give back.

I do this right now (via page objects) by grabbing the tooltip selector from the target, and then checking the content with the selector. I could change this to be a vanilla test helper and PR if it would be useful? 

```
        tooltipSelector() {
          let parentScope = this.__parentTreeNode.scope;
          let localScope = this.scope;
          let tooltipTargetSelector = [parentScope, localScope].join(' ');
          let tooltipId = $(tooltipTargetSelector).attr('aria-describedby');
          let tooltipSelector = `#${tooltipId}[role='tooltip']`;
          return tooltipSelector;
        }
```

**Comment by a15n** [comment]
that would be amazing Ryan. Thank you! As far as I know no one has started working on "Asserting tooltip content matches a string".

**Comment by sir-dunxalot** [comment]
I am working on the position test helper on [this branch](https://github.com/sir-dunxalot/ember-tooltips/tree/position-test-helper) but I am not working on the content test helper.

**Comment by sir-dunxalot** [comment]
@ryanlabouve Let me know if you're not planning on working on the content assertion helper - I can pick it up.

**Comment by ryanlabouve** [comment]
I'll get a branch up tonight! Sorry for the delay.

**Comment by sir-dunxalot** [comment]
No sweat! checking :)

**Comment by sir-dunxalot** [comment]
All test helpers have been added. Great work everyone who contributed!
